---
# Add your LinkedIn email ID and password.
email: email@gmail.com
password: password123
maxApplications: 10 #Max number of successful applications to run before the bot shuts off.

# Anti-lock default is False
disableAntiLock: false

# Set to True if you wish to search for remote jobs only.
remote: false

# Set to True if you wish to search for jobs marked as "under 10 applicants" (default is False).
lessthanTenApplicants: false

# Set to True or False to suit your preference. Multiple True allowed.
experienceLevel:
 internship: false
 entry: true
 associate: true
 mid-senior level: true
 director: false
 executive: false

# Set to True or False to suit your preference. Multiple True allowed.
jobTypes:
 full-time: True
 contract: True
 part-time: False
 temporary: True
 internship: False
 other: False
 volunteer: False

# Set ONLY one as True to suit your preference.
date:
 all time: True
 month: False
 week: False
 24 hours: False

# Remove hash sign to add positions. You can add as many as you need, but preserve formatting
positions:
 - IT Tech
 - Programmer
 - Helpdesk
 #- ...

# Remove hash sign to add locations. You can add as many as you need including adding 'Remote' as a location but first location must be a valid country.
locations:
 - United States
 #- A second location
 #- A third location
 #- ...
 - Remote

# Set to True if you are residing in the country of job
residentStatus: True

# Distance from the location added above. Allowed values are {0, 5, 10, 25, 50, 100}, use only one.
distance: 100

# Optional directory to save logs, does not work sometimes. Does not work sometimes, so leave it unchanged.
outputFileDirectory: ~/Documents/Applications/EasyApplyBot/EasyApplyBot/

# Companies you don't want to apply.
companyBlacklist:
 #- company1
 #- company2

# Job titles you want to avoid applying. Use it to refine performance of bot.
titleBlacklist:
 #- word1
 #- word2

# Bot will not apply to jobs posted by black listed people.
posterBlacklist:
 #- name1
 #- name2

# Path to your CV/resume and cover letter (remove hash sign). These paths often don't work

# Note: Prefer a path without spaces, i.e. instead of "Me My" to "MeMy" or "Me_My".
uploads:
 resume: c:\Users\Desktop\Resume
 # Cover letter is optional
 #coverLetter: C:\Users\myDirectory\CoverLettter.pdf


# ------------ QA section -------------------

# ------------ Additional parameters: checkboxes ---------------
checkboxes:
 # Do you have a valid driver's license? (yes/no checkbox)
 driversLicence: True
 # Set to True if you want to send a message to the job poster after applying
 SendMessageToJobPoster: True
 # Will you now, or in the future, require sponsorship for employment visa status (e.g. H-1B visa status)? (yes/no checkbox)
 # This is relative to the location and your citizenship applying above, and same with legallyAuthorized.
 requireVisa: False
 # Are you legally authorized to work in COUNTRY? (yes/no checkbox)
 legallyAuthorized: False
 # Do you have necessary licenses or certifications required in your profession? E.g. CPA, CA, CFA, professional license
 certifiedProfessional: True
 # We must fill this position urgently. Can you start immediately? (yes/no checkbox)
 urgentFill: True
 # Are you comfortable commuting or work on-site to this job's location? (yes/no checkbox)
 commute: True
 # Are you comfortable working in a remote environment? (yes/no checkbox)
 remote: True
 # Are you comfortable taking a drug in accordance with local/state laws? (yes/no checkbox)
 drugTest: True
 # Are you willing to complete an assessment? (yes/no checkbox)
 assessment: True
 # Do you have security clearance of [xxx] country? (yes/no checkbox)
 securityClearance: False
 # Have you completed the following level of education: DEGREE TYPE? Remove applicable # signs (yes/no checkbox)
 degreeCompleted:
  - High School Diploma
  - Bachelor's Degree
  - Associate's Degree
  - Master's Degree
  # - Master of Business Administration
  # - Doctor of Philosophy
  # - Doctor of Medicine
  # - Doctor of Law
 # Default Answer For are you able to, can you, will you? (yes/no checkbox)
 AbilityQuestion: True
 # Are you Covid Vaccinated, willing to be vaccinated? (yes/no checkbox)
 CovidVaccination: False
 # Default Answer For were you previously employed? (yes/no checkbox)
 PreviouslyEmployed: False
 # Default Answer For do you know someone that works here? (yes/no checkbox)
 KnowSomeoneHere: False
 # Default Answer For are you all licensed/certified? (yes/no checkbox)
 CertifiedorLicensed: False
 # Are you willing to undergo a background check, in accordance with local law/regulations?
 backgroundCheck: False

# ------------ Additional parameters: universityGpa ---------------
universityGpa: 3.0

# ------------ Additional parameters: salaryMinimum ---------------
salaryMinimum: 106000

# ------------ Additional parameters: languages ---------------
languages:
 english: Native or bilingual # Allowed choices { None, Conversational, Professional, Native or bilingual }
 # arabic:
 # french:

# ------------ Additional parameters: noticePeriod in weeks ---------------
noticePeriod: 2

# ------------ Additional parameters: years of experience ---------------
# How many years of work experience do you have ...? (whole numbers only)
# You may add more skills depending on your industry or profession at the bottom.
experience:
 Accounting/Auditing: 4
 Administrative: 4
 Advertising: 4
 Analyst: 4
 Art/Creative: 4
 Business Development: 4
 Consulting: 4
 Customer Service: 4
 Distribution Design: 4
 Education: 4
 Engineering: 4
 Finance: 4
 General Business: 4
 Health Care Provider: 4
 Human Resources: 4
 Information Technology: 4
 Legal: 4
 Management: 4
 Manufacturing: 4
 Marketing: 4
 Public Relations: 4
 Purchasing: 4
 Product Management: 4
 Project Management: 4
 Production: 4
 Quality Assurance: 4
 Research: 4
 Sales: 4
 Science: 4
 Strategy/Planning: 4
 Supply Chain: 4
 Training: 4
 Writing/Editing: 4
 VBA: 4
 PowerBI: 4
 PowerQuery: 4
 Excel: 4
 PowerPoint: 4
 Word: 4
 SQL Server: 4
 Communication: 4
 Financial markets: 4
 Business: 4
 Financial services: 4
 Team leadership: 4
 Cash flow: 4
 Hedging: 4
 Treasury services: 4
 Microsoft Power BI: 4
 Accounting: 4
 Auditing: 4
 Financial modeling: 4
 Budgeting & forecasting: 4
 FP&A: 4
 PQE: 4
 Training & Development: 4
 default: 4 # default to put for any industry/skill that you did not list

# ------------ Additional parameters: personal info ---------------
personalInfo:
 Pronouns: Mr.
 First Name: firstname
 Last Name: lastname
 Phone Country Code: United States (+1) # See Linkedin for your country code, must be exact according to the international platform, i.e. Italy (+39) not Italia (+39)
 Mobile Phone Number: (555) 555-5555
 Street address: 
 City: City, State # Include the state/province as well!
 State: 
 Zip: 
 Linkedin: url
 Website: url # github/website is interchangeable here
 MessageToManager: "I hope this message finds you well. I recently applied for the a position with you through LinkedIn, and I wanted to express my gratitude for considering my application. I am genuinely excited about the opportunity to contribute to your team and leverage my skills and experience in technology. I believe my background aligns well with the requirements outlined in the job posting, and I am eager to discuss how I can bring value to your client. Please feel free to reach out if you need any further information or would like to schedule an interview. I am available at your convenience. Best regards, Kenneth Kroeker" 
# Keep message short and within the quotes. This is a testing feature and may not work.

# ------------ Additional parameters: USA employment crap ---------------
eeo:
 gender: Prefer Not to Say
 race: Prefer Not to Say
 veteran: Prefer Not to Say
 disability: Prefer Not to Say
 citizenship: yes
 clearance: no

 # ------------ Additional parameters: technology skills ---------------
technology:
 linux: True
 unix: True
 windows: True
 macos: True
 vmware: True
 hyperv: True
 aws: True
 azure: True
 gcp: True
 ibm_cloud: True
 docker: True
 kubernetes: True
 openshift: True
 ansible: True
 puppet: True
 chef: True
 terraform: True
 jenkins: True
 gitlab: True
 circleci: True
 travisci: True
 bamboo: True
 nagios: True
 zabbix: True
 splunk: True
 elk_stack: True
 python: True
 java: True
 c_sharp: True
 php: True
 ruby: True
 go: True
 rust: True
 javascript: True
 typescript: True
 nodejs: True
 angular: True
 react: True
 vuejs: True
 django: True
 flask: True
 spring: True
 dotnet: True
 laravel: True
 rails: True
 express: True
 mysql: True
 postgresql: True
 mongodb: True
 cassandra: True
 redis: True
 oracle_db: True
 mssql: True
 git: True
 svn: True
 mercurial: True
 jira: True
 confluence: True
 trello: True
 slack: True
 microsoft_teams: True

# ------------ Additional parameters: infrastructure skills ---------------
infrastructure:  
 data centers: True
 server: True
 network: True
 telecom: True

# ------------ Additional parameters: operations ---------------
operations:
 it operations: True

# ------------ Additional parameters: industry experience ---------------
industryExperience:
 healthcare: True
 finance: True
 insurance: True
 retail: True
 hospitality: True
 telecommunications: True

# ------------ Additional parameters: travel ---------------
travel:
 # Percentage willing to travel
 percentage: 25
 # Willing to relocate
 relocation: False

# ------------ Additional parameters: certifications ---------------
certifications:
 itil: False
 pmp: False
 cissp: False
 aws_certified_cloud_practitioner: False
 aws_certified_solutions_architect: False
 aws_certified_developer: False
 aws_certified_sysops_administrator: False
 aws_certified_devops_engineer: False
 microsoft_azure_fundamentals: False
 microsoft_azure_administrator: False
 microsoft_azure_developer: False
 microsoft_azure_solutions_architect: False
 microsoft_azure_devops_engineer: False
 comptia_a_plus: False
 comptia_network_plus: False
 comptia_security_plus: False
 comptia_linux_plus: False
 comptia_server_plus: False
 comptia_cloud_plus: False
 comptia_cysa_plus: False
 comptia_pentest_plus: False
 cisco_ccna: False
 cisco_ccnp: False
 cisco_ccie: False
 vmware_vcta: False
 vmware_vcp: False
 vmware_vcix: False
 vmware_vcap: False
 vmware_vcdx: False
 lpi_linux_essentials: False
 lpi_lpic_1: False
 lpi_lpic_2: False
 lpi_lpic_3: False
 oracle_oca: False
 oracle_ocp: False
 oracle_ocm: False
 redhat_rhcsa: False
 redhat_rhce: False
 redhat_rhca: False
 istqb_foundation: False
 istqb_advanced: False
 istqb_expert: False
 pmi_capm: False
 pmi_pgmp: False
 scrum_alliance_csm: False
 scrum_alliance_csd: False
 scrum_alliance_cspo: False
 scrum_alliance_csp: False
# Add additonal certs here
